### ISSUE TITLE
Not Work in Big Sur

### ISSUE THREAD

**Issue by AleksIralda** [miclgael/alfred-mamp-workflow#3]
Erratic behavior in
MacOS Big Sur 11.2.3
MAMP Pro 5.7
Alfred 4.3.2

Stop Servers not work, Start Server works but duplicate the running instance (Open new Dock Icon and/or Open other elephant Icon in Menubar). I'm Trying create my own workflow because but I can't make work properly.

**Comment by miclgael** [comment]
Thanks @AleksIralda 

I believe that to be the appropriate behaviour, at least for now. I don’t usually have a MAMP process running already when starting and stopping.

 I have seen this happen but didn’t really consider it a deal breaker. If you want to fork and make a PR I’ll happily merge it. I might make a note of this in the README for now, as I don’t know when I’ll have time to play around again.

If you do manage to make your own from scratch I’d love to see a link to it as well. 

Thanks again for the issue. I’ll leave it open for now.

**Comment by miclgael** [comment]
Hey again @AleksIralda 

Had some time this morning to play around could you please give this a try?

Open up the workflow in Alfred and change the script to the following

```bash
#!/bin/bash

query=$1

# Deprecated method:
# open /Applications/MAMP\ PRO
# /Applications/MAMP\ PRO.app/Contents/MacOS/MAMP\ PRO cmd $query

# First, open the MAMP Pro app.
open /Applications/MAMP\ PRO.app

# Jump into MAMP built-in scripts
cd /Applications/MAMP/bin

# Jump into one of the MAMP built-in scripts

# START SERVERS
if [ "$query" = 'startServers' ]; then
  ./start.sh
fi

# STOP SERVERS
if [ "$query" = 'stopServers' ]; then
  ./stop.sh
fi

exit 0
```

![MAMP Pro Shortcuts script in Alfred UI](https://user-images.githubusercontent.com/4301358/111085766-dca9a680-856c-11eb-8149-4df3abfcba43.png)

Manually stop the servers, close MAMP Pro and try the `start` command. 

I think this is a better fix. I'm gonna do a new release in case thats easier.

**Comment by miclgael** [comment]
Link to release: https://github.com/miclgael/alfred-mamp-workflow/releases/tag/v0.0.5-preview

**Comment by miclgael** [comment]
Closed for now. 
Thanks again.
